version: "3"
services:
  my_postgres12:
    image: "postgres:12"
    container_name: "my_postgres12"
    env_file:
      - pg.env
    ports:
      - "54320:5432"
    volumes:
      - ./pg_data/:/var/lib/postgresql/data/
      - ./trigger_test:/trigger_test

    networks:
      - pg
networks:
  pg:
