- hosts: eks_master
  vars:
    # helm_chart_url: "https://openebs.github.io/charts"
    helm_chart_url: "https://charts.helm.sh/stable"
    helm_key_repo: "https://baltocdn.com/helm/signing.asc"
  tasks:
    - name: Install packages
      apt:
        name: "{{ item }}"
        force: yes
      become: true
      loop:
        - apt-transport-https
        - python3-pip
    - name: Install pip dependencies
      pip:
        name: "{{ item }}"
      loop:
        - openshift
        - k8s
        - setuptools
    - name: Adding key
      apt_key:
        url: "{{ helm_key_repo }}"
        state: present
      become: true

    - name: Add sources list Helm
      ansible.builtin.apt_repository:
        repo: deb https://baltocdn.com/helm/stable/debian/ all main
        state: present
      become: true
    - name: apt-get update
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true
    - name: Install Helm
      apt:
        name: helm
      become: true
    - name: Add OpenEBS helm repository
      community.kubernetes.helm_repository:
        name: openebs
        repo_url: "{{ helm_chart_url }}"
      ignore_errors: yes
    - name: Update Helm Repo
      command: helm repo update
    # Create namespace for Storage
    - name: Create OpenEBS namespace
      community.kubernetes.k8s:
        name: openebs
        api_version: v1
        kind: Namespace
        state: present
    - name: Install Open EBS
      community.kubernetes.helm:
        name: openebs
        # name: openebs
        chart_ref: openebs/openebs
        release_namespace: openebs

# - name: Add OpenEBS helm repository
#   kubernetes.core.helm_repository:
#     name: openebs
#     update_repo_cache: true
#     repo_url: "{{ helm_chart_url }}"